name: Image Security
description: Analista Imagens
inputs:
  version:
    required: true
  application:
    required: true

runs:
  using: composite
  steps:
    - name: Run Trivy on image
      env:
        APPLICATION: ${{ inputs.application }}
        VERSION: "${{ inputs.version }}"
      shell: bash
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          ghcr.io/aquasecurity/trivy:0.70.0 image \
          --format table \
          --severity CRITICAL,HIGH \
          --exit-code 0 \
          "$APPLICATION:$VERSION"
