name: Dast
description: Analise Dinamica de código
inputs:
  hostname:
    required: true
  time:
    required: false
    default: 0

runs:
  using: composite
  steps:
    - name: Wait before starting DAST
      env:
        TIME: ${{ inputs.time }}
      shell: bash
      if: inputs.time > 0
      run: sleep $TIME
    - name: Run DAST
      shell: bash
      env:
        HOSTNAME: ${{ inputs.hostname }}
      run: |
        {
          echo "### 🔍 DAST"
          echo '```'
          docker run -t zaproxy/zap-stable zap-baseline.py -t $HOSTNAME -s -l WARN || true
          echo '```'

        } | tee -a "$GITHUB_STEP_SUMMARY"